import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBarLinkType } from "@/lib/types/sidebar";
import SideBar from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const sideBarLinks: SideBarLinkType[] = [
  { name: "Login", path: "/login" },
  { name: "Quiz Creator", path: "/quizcreate" },
  { name: "Profile", path: "/userprofile" },
  { name: "Settings", path: "/settings" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SideBar sideBarLinks={sideBarLinks} />
        <main className="sm:ml-64 flex-1">{children}</main>
      </body>
    </html>
  );
}
